package Game;

import java.util.ArrayList;

public class Dialog {
	ArrayList<String> social = new ArrayList<String>();
	public Dialog(){
		social.add("I'm raising Pokemon too! When they get strong, they can protect me!");
		social.add("Technology is incredible! You can now store and recall items and Pokemon as data via PC!");
		social.add("See those ledges along the road? It's a bit scary, but you can jump from them. You can get around quicker that way.");
		social.add("Those poke balls at your waist! You have Pokemon! It's great that you can carry and use Pokemon any time, anywhere!");
		social.add("There's a Pokemon center in every town ahead. They don't charge any money either!");
		social.add("Pokemon Centers heal your tired, hurt or fainted Pokemon!");
		social.add("Coming up with nicknames is fun, but hard. Simple names are the easiest to remember.");
		social.add("Rattata may be small, but its bite is wicked! Did you get one?");
		social.add("I ran out of poke balls to catch Pokemon with! You should carry extras!");
		social.add("Many Pokemon live only in forests and caves. You need to look everywhere to get different kinds!");
		social.add("It's rumored that Clefairys came from the moon! They appeared after Moon Stone fell on Mt.Moon.");
		social.add("Yawn! When Jigglypuff sings, Pokemon get drowsy... ...Me too... Snore...");
		social.add("Good things can happen if you raise Pokemon diligently, even the weak ones!");
		social.add("A shady, old man got me to buy this really weird fish Pokemon!	It's totally weak and it cost P500!");
		social.add("Pokemon learn new techniques as they grow! But, some moves must be taught by the trainer!");
		social.add("Pokemon become easier to catch when they are hurt or asleep! But, it's not a sure thing!");
		social.add("Our Pokemon's an outsider, so it's hard to handle. An outsider is a Pokemon that you get in a trade. It grows fast, but it may ignore an unskilled trainer in battle! If only we had some BADGEs...");
		social.add("I want a Pikachu! It's so cute! I asked my Daddy to catch me one!");
		social.add("Ouch! I tripped over a rocky Pokemon, Geodude!");
		social.add("If you have too many Pokemon, you should store them via PC!");
		social.add("I've 6 Poke Balls set in my belt. At most, you can carry 6 Pokemon.");
		social.add("Use Repel to keep bugs and weak Pokemon away. Put your strongest Pokemon at the top of the list for best results!");
		social.add("Have you seen any Rare Candy? It's supposed to make Pokemon go up one level!");
		social.add("It is true that a higher level Pokemon will be more powerful... But, all Pokemon will have weak points against specific types. So, there is no universally strong Pokemon.");
		social.add("Even if they are the same level, Pokemon can have very different abilities. A Pokemon raised by a trainer is stronger than one in the wild.");
		social.add("There are evil people who will use Pokemon for criminal acts. Team Rocket traffics in rare Pokemon. They also abandon Pokemon that they consider not to be popular or useful.");
		social.add("I think Pokemon can be good or evil. It depends on the trainer.");
		social.add("I just love my Seel! It squeals when I hug it!");
		social.add("Humph! My Pikachu is twice as cute as that one!");
		social.add("Did you hear about Snorlax? All it does is eat and sleep!");
		social.add("My buddy, Machoke, is super strong! He has enough Strength to move big rocks!");
		social.add("Pokemon can CUT down small bushes.");
		social.add("Ah yes, I have seen some Pokemon ferry people across the water!");
		social.add("Have you gone to the Safari Zone? It has many rare kinds of Pokemon!!");
		social.add("A fainted Pokemon can't fight. But, it can still use moves like CUT!");
		social.add("I sold a useless nugget for P5000!");
		social.add("The element types of Pokemon make them stronger than some types and weaker than others!");
		social.add("Cubones wear skulls, right? People will pay a lot for one!");
		social.add("Team Rocket will do anything for the sake of gold!");
		social.add("You know revive? It revives any fainted Pokemon!");
		social.add("What are you staring at?");
		social.add("Captured Pokemon are registered with an ID No. and OT, the name of the Original Trainer that caught it!");
		social.add("You can identify Pokemon you got in trades by their ID Numbers!");
		social.add("I heard something useful. You can run from wild Pokemon by distracting them with a POKE DOLL!");
		social.add("What do you want? Get lost!");
		social.add("Ow! Watch where you're walking!");
		social.add("Get out of the way!");
		social.add("Revive is costly, but it revives fainted Pokemon!");
		social.add("Max Repel lasts longer than SUPER REPEL for keeping weaker Pokemon away!");
		social.add("If you're studying Pokemon, visit the Safari Zone. It has all sorts of rare Pokemon.");
		social.add("You can't win with just one strong Pokemon. It's tough, but you have to raise them evenly.");
		social.add("My Eevee evolved into Flareon! But, a friend's Eevee turned into a Vaporeon! I wonder why?");
		social.add("Do you have any friends? Pokemon you get in trades grow very quickly. I think it's worth a try!");
		social.add("Pokemon can still learn techniques after canceling evolution. Evolution can wait until new moves have been learned.");
		social.add("You can cancel evolution. When a Pokemon is evolving, you can stop it and leave it the way it is.");
		social.add("It never hurts to have extra items!");
		social.add("Oh! Your Pokemon is adorable! I wish I had one!");
		social.add("Pokemon hide in the grass. Who knows when they'll pop out...");
		social.add("Yo. How are your Pokemon? If they're weak and not ready for battle, keep out of the grass.");
		social.add("I wanted to take a break, so I saved to record my progress.");
		social.add("I'm waiting for Pokemon that appear only in the morning.");
		social.add("I'm waiting for Pokemon that appear only at night.");
		social.add("When you're with Pokemon, going anywhere is fun.");
		social.add("When I was walking in the grass, a bug Pokemon poisoned my Pokemon! I just kept going, but then my Pokemon fainted. You should keep an ANTIDOTE with you.");
		social.add("When I get older, I'm going to be a GYM LEADER! I make my Pokemon battle with my friend's to make them tougher!");
		social.add("Check trees for berries. They just drop right off.");
		social.add("I'm not a trainer. But if you look one in the eyes, prepare to battle.");
		social.add("... Hnuurg... Huh? I walked too far today looking for Pokemon. My feet hurt and I'm sleepy... If I were a wild Pokemon, I'd be easy to catch... ...Zzzz...");
		social.add("Pokemon are smart. They won't obey a trainer they don't respect. Without the right Gym Badges, they will just do as they please.");
		social.add("When you first catch a Pokemon, it may be weak. But it will eventually grow to be strong. It's important to treat Pokemon with love.");
		social.add("A Pokemon holding a BERRY will heal itself in battle. Many other items can be held by Pokemon... It sure it tough taking notes...");
		social.add("A Pokemon you get in a trade grows quickly. But if you don't have the right Gym Badge, they may disobey you.");
		social.add("Hey! I'm no trainer but I can give some advice! Believe me! If you believe, a championship dream can come true. You believe? Then listen. The grass-type is weak against the flying-type. Keep this in mind.");
		social.add("What should I make my Pokemon hold? Maybe an item that increases attack power...");
		social.add("Do you know about Apricorns? Crack one open, hollow it out and fit it with a special device. Then you can catch Pokemon with it. Before POKE BALLS were invented, everyone used APRICORNS.");
		social.add("Do your Pokemon know HM moves? Those moves can be used even if your Pokemon has fainted.");
		social.add("A higher level Pokemon doesn't always win. After all, it may have a type disadvantage. I don't think there is a single Pokemon that is the toughest.");
		social.add("I wonder how many kinds of Pokemon there are in the world.");
		social.add("I keep losing in battles, and my Pokemon end up fainting... Maybe that's why my Pokemon don't like me much...");
		social.add("Once while I was battling, my Pokemon couldn't make any moves. The Power Points, or PP, of its moves were all gone.");
		social.add("Sometimes, a healthy Pokemon may be unable to use its moves. If that happens, heal it at a Pokemon Center or use an item.");
		social.add("Hey. I love strong Pokemon. I feed them Protein to crank up their attack.");
		social.add("Iron adds to your Pokemon's Defense.");
		social.add("Some Pokemon evolve only by being traded. I know of four: Machoke, Kadabra, Haunter and, um, Graveler. I heard there are others too.");
		social.add("If you use Revive, a Pokemon that's fainted will wake right up.");
		social.add("My Eevee evolved into an Espeon. But my friend's Eevee turned into an Umbreon. I wonder why? We both were raising our Eevee in the same way..");
		social.add("This happened when I was young. The sky suddenly turned black. A giant flying Pokemon was blocking out the sun. I wonder what that Pokemon was? It was like a bird and a dragon.");
		social.add("Pokemon get more friendly if you spend time with them.");
		social.add("My Butterfree came from my boyfriend overseas. It carried some mail from him. Want to know what it says? Let's see... Nope! It's a secret!");
		social.add("Do your Pokemon already know the move for carrying people on water?");
		social.add("Some Boulders can be crushed. They may be hiding something. Your Pokemon could use ROCK SMASH to break them.");
		social.add("I stop my Pokemon from evolving too early. I make them learn certain moves before I let them evolve.");
		social.add("Pokemon do become stronger when they evolve, but they also learn moves more slowly.");
		social.add("Did my eyes deceive me? I saw a red Gyarados... But I thought Gyarados were usually blue?");
		social.add("Are you going to make your Pokemon forget some moves?");
		social.add("You can't buy Max Revive, but it fully restores a fainted Pokemon. Beware--it won't restore PP, the power points needed for moves.");
		social.add("Max Repel keeps weak Pokemon away from you. It's the longest lasting of the REPEL sprays.");
		social.add("You can't climb ledges. But you can jump down from them to take a shortcut.");
		social.add("Going into an alley for the first time makes me sorta anxious.");
		social.add("I want to become stronger, but I'm not good yet... Could you show me how sometime?");
		social.add("You need a poke flute to wake sleeping Pokemon. Every trainer has to know that!");
		social.add("Repel is a necessity if you are going to explore a cave. Even though I like exploring, I still haven't made it to all the caves.");
		social.add("Ah... I'm so happy...");
		social.add("Looking at the ground while I was walking made me dizzy.");
		social.add("I can't decide which Pokemon I should use this TM On...");
		social.add("I want PP Up, so I can raise the PP of moves. But you can't buy it...");
		social.add("You're working on a Pokedex? That's really something. Don't give up!");
		social.add("Most Pokemon get drowsy if they hear a Jigglypuff singing. There are several moves that can be used only while a Pokemon is asleep.");
		social.add("There once was a weird old man who sold Magikarp. He was saying that Magikarp were excellent!");
		social.add("I heard that when the sun goes down in some places, Clefairy come out to play.");
		social.add("Hi! Wow, I'm glad to see you. You're the first visitor I've had in a long time. I'm super-happy!");
		social.add("My dream is to become a gym leader.");
		social.add("Whew... I'm taking a rest from Pokemon battles.");
		social.add("I'm raising Pokemon too. They serve as my private guards.");
		social.add("I'm all sweaty.");
		social.add("Good evening!");
		social.add("Oh, wow! Will you quit bothering me?");
		social.add("There's something I really want, but I don't have the necessary cash... Maybe I'll sell off the berries I've collected...");
		social.add("Hehehe, I snuck out from work.");
		social.add("It's a grueling task, not being able to use items in battle. Making your Pokemon hold items is the key to winning battles.");
		social.add("I love showing off the Pokemon that I've raised. Don't you? I'm going to get into a bunch of battles, and show off my Pokemon!");
		social.add("My grandma is into warding off what she believes to be evil spirits.");
		social.add("I have a hard time learning the names of items and how they are supposed to be used...");
		social.add("Look for Pokemon in grassy areas!");
		social.add("To evolve, some Pokemon grow, others use the effects of STONES.");
		social.add("Have you gotten a fishing rod? You can catch Pokemon by fishing.");
		
		System.out.println("Added " + social.size() + " unique dialogs for NPC's!");
	}
}
